import './globals.css';

export const metadata = {
  title: 'Next 13 App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white flex justify-center">
        {children}
      </body>
    </html>
  )
};